[config.wallpaper]
version_check = false
command = "swww"

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.cava]
input_path = '~/.config/matugen/templates/matugen-cava'
output_path = '~/.config/cava/config'
post_hook = "pkill -USR1 cava"

[templates.niri]
input_path = '~/.config/matugen/templates/niri-colors.kdl'
output_path = '~/.config/niri/colors.kdl'

[templates.fcitx5]
input_path = '~/.config/matugen/templates/fcitx5-theme.conf'
output_path = '~/.local/share/fcitx5/themes/Matugen/theme.conf'
post_hook= 'fcitx5 -r -d & disown '

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprlock.conf'
output_path = '~/.config/hypr/colors.conf'


[templates.btop]
input_path = '~/.config/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'

[templates.Colorsheme]
input_path = '~/.config/matugen/templates/Colorscheme.qml'
output_path = '~/.config/quickshell/config/Colorsheme.qml'


